### ISSUE TITLE
Error during the cloning the repository with git clone

### ISSUE THREAD

**Issue by rafaesc** [CroudSupport/Croud-Style-Guide#26]
When I try to clone, the repository created didn't work fine, because said me that I have change without commit, but recently I had cloned it.

![](https://i.imgur.com/IQcpcE5.png)

I tried in a Windows, I guess that the problem it's the file `src/Icon` that it tries to download.

Regards

**Comment by BrockReece** [comment]
@rafaesc thanks for the heads up on this, I have removed the problem file in a PR that is awaiting review.

**Comment by BrockReece** [comment]
This should have now been fixed in v1.5.1
